window.ETR = window.ETR || {};
window.ETR.LocalResources = {
    CommonDecadeNameGenitiveFirst: 'First ten-day of',
    CommonDecadeNameGenitiveSecond: 'Second ten-day of',
    CommonDecadeNameGenitiveThird: 'Third ten-day of',
    CommonDecadeNameNominativeFirst: 'First ten-day of',
    CommonDecadeNameNominativeSecond: 'Second ten-day of',
    CommonDecadeNameNominativeThird: 'Third ten-day of',
    CommonUserMessageErrorOnFileUpload: 'Error occured on file upload.',
    CommonUserMessageDuplicateUploadFileName: 'File with the same name already uploaded',
    CommonUserMessageYes: 'Yes',
    CommonUserMessageNo: 'No',
    CommonPagedListFirstPage: 'First page',
    CommonPagedListLastPage: 'Last page',
    CommonPagedListNextPage: 'Next page',
    CommonPagedListPage: 'Page',
    CommonPagedListPageOf: 'of {0}',
    CommonPagedListPrevPage: 'Previous page',
    CommonPagedListTotalRecords: 'Displaying records {0} - {1} of {2}. Page size',
    CommonUserMessageTotalRecords: 'Loaded records {0} of {1} ',
    CommonListTotalRecords: 'Display {0} records',
    CommonListShowMore: 'Show more',
    CommonUserMessageNotFound: 'Requested resource was not found.',
    CommonUserMessageForbidden: 'Access error. You haven&#39;t enough rights to perform this operation.',
    CommonUserMessageErrorOnFileDownload: 'Error occured while uploading file',
    CommonUserMessageInitialListMessage: 'Enter search options and press "Show" button',
    CommonUserMessageFailedListMessage: 'An error has occured since the last data loading',
    CommonUserMessageCancelledListMessage: 'Data loading was cancelled',
    CommonUserMessageNoData: 'There are no data found',
    CommonUserMessageShowData: 'Show',
    CommonUserMessageStopLoading: 'Press to stop data loading'
};
