window.ETR = window.ETR || {};
window.ETR.LocalResources = {
    CommonDecadeNameGenitiveFirst: 'Первую декаду',
    CommonDecadeNameGenitiveSecond: 'Вторую декаду',
    CommonDecadeNameGenitiveThird: 'Третью декаду',
    CommonDecadeNameNominativeFirst: 'Первая декада',
    CommonDecadeNameNominativeSecond: 'Вторая декада',
    CommonDecadeNameNominativeThird: 'Третья декада',
    CommonUserMessageErrorOnFileUpload: 'При попытке загрузить файл произошла ошибка.',
    CommonUserMessageDuplicateUploadFileName: 'Файл с таким названием уже загружен',
    CommonUserMessageYes: 'Да',
    CommonUserMessageNo: 'Нет',
    CommonPagedListFirstPage: 'Первая страница',
    CommonPagedListLastPage: 'Последняя страница',
    CommonPagedListNextPage: 'Следующая страница',
    CommonPagedListPage: 'Страница',
    CommonPagedListPageOf: 'из {0}',
    CommonPagedListPrevPage: 'Предыдущая страница',
    CommonPagedListTotalRecords: 'Показаны записи {0} - {1} из {2}. Размер страницы',
    CommonUserMessageTotalRecords: 'Показано записей {0} из {1}',
    CommonListTotalRecords: 'Итого {0} записей',
    CommonListShowMore: 'Показать еще',
    CommonUserMessageNotFound: 'Запрошенный ресурс не найден.',
    CommonUserMessageForbidden: 'Ошибка доступа. У Вас нет прав на выполнение данной операции.',
    CommonUserMessageErrorOnFileDownload: 'При загрузке файла произошла ошибка',
    CommonUserMessageInitialListMessage: 'Укажите параметры поиска и нажмите кнопку "Показать"',
    CommonUserMessageFailedListMessage: 'При последней загрузке данных произошла ошибка',
    CommonUserMessageCancelledListMessage: 'Загрузка данных была отменена',
    CommonUserMessageNoData: 'Данные не найдены',
    CommonUserMessageShowData: 'Показать',
    CommonUserMessageStopLoading: 'Нажмите для остановки загрузки данных'
};

